config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dupaks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dupak.rb
class Dupak < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dupaks_controller.rb
class DupaksController < ApplicationController

  def index
    @dupaks = Dupak.all
  end

  def show
    @dupak = Dupak.find(params[:id])
  end

  def new

  end
  def create
    @dupak = Dupak.new(dupak_params)
 
    @dupak.save
    redirect_to @dupak 
  end

  private
  def dupak_params
    params.require(:dupak).permit(:dupaka_name, :with_who)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dupaks_helper.rb
module DupaksHelper
end

app/views/dupaks/index.html.erb
<h1>Dupaki !!!</h1>
 
<table>
  <tr>
    <th>Jaka Taka </th>
    <th>With who</th>
    <th></th>
  </tr>
 
  <% @dupaks.each do |dupak| %>
    <tr>
      <td><%= dupak.dupaka_name %></td>
      <td><%= dupak.with_who %></td>
      <td><%= link_to 'Show', dupak_path(dupak) %></td>
    </tr>
  <% end %>
</table>

app/views/dupaks/new.html.erb
<h1>Miala byc Dupaka nie wyszło !</h1>


<%= form_with scope: :dupak, url: dupaks_path, local: true do |form| %>
  <p>
    <%= form.label :dupaka_name %><br>
    <%= form.text_field :dupaka_name %>
  </p>
 
  <p>
    <%= form.label :with_who %><br>
    <%= form.text_area :with_who %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/dupaks/show.html.erb
<p>
  <strong>Dupaka name:</strong>
  <%= @dupak.dupaka_name %>
</p>
 
<p>
  <strong>With who?:</strong>
  <%= @dupak.with_who %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VagrantDevEnv</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>